# choose image download URL from "os" and "flavor" variable
- name: choosing raspbian lite image
  set_fact:
    download_image_url: "https://downloads.raspberrypi.org/raspbian_lite_latest"
  when: download_os == "raspbian" and download_os_flavor == "lite"

- name: choosing raspbian full image
  set_fact:
    download_image_url: "https://downloads.raspberrypi.org/raspbian_full_latest"
  when: download_os == "raspbian" and download_os_flavor == "full"

# create the download_workdir that will contain the decompressed image and mountpoints
- name: creating workdir
  file:
    path: "{{ download_workdir }}"
    state: directory

- name: "downloading OS image ({{ download_os }} {{ download_os_flavor }})"
  get_url:
    url:  "{{ download_image_url }}"
    dest: "{{ download_workdir }}/os_image"
  register: download

- name: "extracting OS image"
  unarchive:
    remote_src: yes
    list_files: yes
    src: "{{ download.dest }}"
    dest: "{{ download_workdir }}/"
  register: archive
  when: download_image_filename is not defined

- name: "remembering OS image filename ({{ archive.files[0] }})"
  set_fact:
    download_image_filename: "{{ archive.files[0] }}"
  when: download_image_filename is undefined
