- name: "setting hostname (from {{ hostname_template }})"
  template:
    src: "{{ hostname_template }}"
    dest: "{{ mount_root }}/etc/hostname"
    owner: root
    group: root
    mode: '0600'
  become: yes
