---
# burn minimal raspberry OS with only most basic modifications to sdcard
- hosts: localhost
  roles:
    - download
    - mount
    - hostname
    - ssh-enable
    - sshd_config
    - wifi
    - umount
    - sdcard
