---
# burn vanilla raspberry OS with only most basic modifications to sdcard
- hosts: localhost
  roles:
    - image-download
    - image-mount
    - hostname
    - ssh
    - wifi
    - image-unmount
    - image-burn
