# umount partitions
- name: unmounting /root
  command: umount "{{ workdir }}/root"
  args:
    warn: no
  become: yes
- name: unmounting /boot
  command: umount "{{ workdir }}/boot"
  args:
    warn: no
  become: yes
- # detach loopback
  name: detaching image from loopback device
  shell: losetup -d "{{ loopback_dev }}"
