- name: "copying wpa_supplicant.conf file (from {{ wifi_wpa_supplicant_template }})"
  template:
    src: "{{ wifi_wpa_supplicant_template }}"
    dest: "{{ mount_boot }}/wpa_supplicant.conf"
  become: yes
