# choose image download URL from "os" and "flavor" variable
- name: choosing raspbian lite image
  set_fact:
    image_url: "https://downloads.raspberrypi.org/raspbian_lite_latest"
  when: os == "raspbian" and os_flavor == "lite"

- name: choosing raspbian full image
  set_fact:
    image_url: "https://downloads.raspberrypi.org/raspbian_full_latest"
  when: os == "raspbian" and os_flavor == "full"

# create the workdir that will contain the decompressed image and mountpoints
- name: creating workdir
  file:
    path: "{{ workdir }}"
    state: directory

- name: "downloading OS image ({{ os }} {{ os_flavor }})"
  get_url:
    url:  "{{ image_url }}"
    dest: "{{ workdir }}/os_image"
  register: download

- name: "extracting OS image"
  unarchive:
    remote_src: yes
    list_files: yes
    src: "{{ download.dest }}"
    dest: "{{ workdir }}/"
  register: archive
  when: image_filename is not defined

- name: "remembering OS image filename ({{ archive.files[0] }})"
  set_fact:
    image_filename: "{{ archive.files[0] }}"
  when: image_filename is undefined
