- name: enabling ssh server
  file:
    path: "{{ mount_boot }}/ssh"
    state: touch
  become: yes

- name: creating ~/.ssh
  file:
    path: "{{ mount_root }}/home/pi/.ssh"
    state: directory
    mode: 0700
    owner: "1000"
    group: "1000"
  become: yes

- name: generating ssh key
  openssh_keypair:
    type: ed25519
    path: "{{ mount_root }}/home/pi/.ssh/id_ed25519"
    mode: 0600
    owner: "1000"
    group: "1000"
  when: ssh_generate_keypair

- name: copying authorized_keys file
  template:
    src: "{{ ssh_authorized_keys_template }}"
    dest: "{{ mount_root }}/home/pi/.ssh/authorized_keys"
    mode: 0600
    owner: "1000"
    group: "1000"
  become: yes
