- name: setting up loopback device (linux)
  import_tasks: mount-linux.yml
  when: ansible_facts.system == "Linux"

- name: setting up loopback device (mac)
  import_tasks: mount-mac.yml
  when: ansible_distribution == 'MacOSX'
