- name: "unmounting {{ download_workdir }}/root"
  command: umount "{{ download_workdir }}/root"
  register: unmount_root
  changed_when: unmount_root.rc == 0
  args:
    warn: no
  become: yes

- name: "unmounting {{ download_workdir }}/boot"
  command: umount "{{ download_workdir }}/boot"
  register: unmount_boot
  changed_when: unmount_boot.rc == 0
  args:
    warn: no
  become: yes

- name: detaching image from loopback device
  command: losetup -d "{{ mount_loopback_dev }}"
  register: loopback_detach
  changed_when: loopback_detach == 0
