# copy custom sshd_config
- name: copying sshd_config file
  template:
    src: "{{ sshd_config_template }}"
    dest: "{{ mountpoint_root }}/etc/ssh/sshd_config"
    mode: 600
    owner: root
    group: root
  become: yes
